trigger:
- main
- develop

pool:
  vmImage: 'windows-latest'

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'
  angularBuildOutput: ''
  aspNetCoreProjectPath: '$(Build.SourcesDirectory)/AzureCICD'

steps:
- task: NuGetToolInstaller@1

- task: NuGetCommand@2
  inputs:
    restoreSolution: '$(solution)'

- task: NodeTool@0
  inputs:
    versionSpec: '18.x'
  displayName: 'Install Node.js'

- script: npm install
  workingDirectory: $(Build.SourcesDirectory)/AzureCICDUI
  displayName: 'npm install for Angular'

- script: npm run build:prod
  workingDirectory: $(Build.SourcesDirectory)/AzureCICDUI
  displayName: 'Angular build'

- task: CopyFiles@2
  inputs:
    SourceFolder: '$(Build.SourcesDirectory)/AzureCICDUI/dist/azure-cicdui'
    Contents: '**'
    TargetFolder: '$(Build.SourcesDirectory)/AzureCICD/wwwroot'
  displayName: 'Copy Angular build to ASP.NET wwwroot'

- task: VSBuild@1
  inputs:
    solution: '$(solution)'
    msbuildArgs: '/p:DeployOnBuild=true /p:WebPublishMethod=Package /p:PackageAsSingleFile=true /p:SkipInvalidConfigurations=true /p:PackageLocation="$(build.artifactStagingDirectory)"'
    platform: '$(buildPlatform)'
    configuration: '$(buildConfiguration)'

- task: PublishBuildArtifacts@1
  inputs:
    pathtoPublish: '$(build.artifactStagingDirectory)'
    artifactName: 'drop'
    publishLocation: 'Container'
